### ISSUE TITLE
Upload progress indicator

### ISSUE THREAD

**Issue by GermainZ** [HalosGhost/pbpst#1]
A progress indicator would be great, especially for larger uploads.

For bonus points, also add an ILoveCandy easter egg.

**Comment by HalosGhost** [comment]
Consider this a planned feature. As I will be leveraging `libcurl`, there are already built-in utilities to manage this.

Plan is for there to be something like `-#` (as in `curl`) that will show a progress meter. I will have to consider whether or not to offer a progress meter on all pastes and then have `-#` do a progress bar rather than the simpler meter.

Thoughts?

**Comment by GermainZ** [comment]
> I will have to consider whether or not to offer a progress meter on all pastes

Can it be shown after a few seconds if the upload isn't completed yet? Alternatively, make it a switch.

> and then have -# do a progress bar rather than the simpler meter.

¯\o/¯

**Comment by HalosGhost** [comment]
I definitely don't want to have it delayed in showing up. The question is whether or not there should be a default textual meter (as there is in `curl`) and then have `-#` display a pseudo-graphical meter instead or just forego the textual meter altogether and have `-#` show the pseudo-graphical meter and be done with it.

**Comment by GermainZ** [comment]
I don't mind either. The pseudo-graphical meter could also include
speed/percentage/time left like pacman does. Could the default textual
meter be better for scripts, though?

**Comment by HalosGhost** [comment]
I think having the textual meter as default actually makes it harder to script around (and would probably require the addition of a `--quiet` switch).

So, I'm leaning towards having no feedback (till error or completion) for the user unless they've passed `--verbose` which I pass directly to `libcurl`, or if they ask for `-#` where I won't give them verbose libcurl output but will instead give them a fancy progress bar. And sure, having the current speed listed isn't hard either. Percent seems redundant with a fancy bar, and ETA might be more difficult, but we'll see.

**Comment by HalosGhost** [comment]
closed via 99d0085
