### ISSUE TITLE
Implement support for the Rendering Handler

### ISSUE THREAD

**Issue by HalosGhost** [HalosGhost/pbpst#14]
Prerequisites
- [x] #12 

pb has the ability to take a paste in mdown or rst and render it to html. This is performed with the rendering handler. Luckily, all we have to do is modify the URL returned to the user if this option is requested (yes, this means the user will be able to request the rendering handler on a paste where that makes no sense—just like they would be able to do if they go to the web browser and do it manually).

**Comment by buhman** [comment]
How does this work?

```
pbpst -Sr < blah
<browser opened?>
```

**Comment by HalosGhost** [comment]
No, it will just return the URL with the `/r/` route added.

**Comment by HalosGhost** [comment]
via a0ac82c
