### ISSUE TITLE
Web Gallery

### ISSUE THREAD

**Issue by meskarune** [HalosGhost/pbpst#21]
Prerequisites:
- [ ] #12

Have an html/css/js web front end that has a gallery of pastes pulled from the json db.

Ideally, this will include the following:
- [ ] A single `.htm` with embedded CSS and JS
- [ ] A command-line option which launches `$BROWSER` pointing to the `.htm`

**Comment by HalosGhost** [comment]
Once the local db is implemented, work on the page can begin. There is, however, one hurdle we will need to overcome: the local database is not guaranteed to be in any specific location.

So, the page will either have to have an input box where the user specifies the db location (with a sane default, perhaps), or it'll need some way of locating it. I greatly prefer the former of those two options. Thoughts?

**Comment by kyrias** [comment]
Would make more sense to just require the DB to be in the same directory as the front end thing.

**Comment by HalosGhost** [comment]
That guarantee cannot be made. We _could_ do it the other way around and create the webpage wherever the database is, but since one of the planned features is to allow the user to specify a location to use at-runtime, we would have to be willing/able to create the webpage every time a new database location is specified.

While I like the idea of shipping this web gallery, I do not like the idea of duplicating it for each database.

**Comment by kyrias** [comment]
Why can't it? The user would just have to copy the embedded web gallery page and the DB to wherever they want to serve it?

**Comment by HalosGhost** [comment]
First, the notion of this is not to be served. Just to have a simple, fancy way of auditing your own pastes. Second, I'd like to have a solution that JustWorks™, and does so consistently (even if that consistency is that the user has to specify the db location).

The plan is to eventually offer a simple cli option for `pbpst` that would just launch `$BROWSER` with the location of the webgallery htm as an argument. if the web gallery does not have a static location, that cli option is much more difficult to implement.

**Comment by kyrias** [comment]
> First, the notion of this is not to be served. Just to have a simple, fancy way of auditing your own pastes. Second, I'd like to have a solution that JustWorks™, and does so consistently (even if that consistency is that the user has to specify the db location).

There's not really any difference.

> The plan is to eventually offer a simple cli option for pbpst that would just launch $BROWSER with the location of the webgallery htm as an argument. if the web gallery does not have a static location, that cli option is much more difficult to implement.

So then just have a query string for the DB path.

**Comment by HalosGhost** [comment]
Can that be done with pure JS/HTML?

**Comment by kyrias** [comment]
Yes.

**Comment by HalosGhost** [comment]
Great! in that case, then we can just pass the db locaiton to the page on the cli with no issues. @meskarune, does that sound okay?

**Comment by HalosGhost** [comment]
At the moment, it seems like this might not be doable with (good) restrictions that browsers place on JS. If, at any time, it seems that this can be implement simply and statically, I will be happy to reopen and revisit.
