### ISSUE TITLE
signal handling; lock cleanup

### ISSUE THREAD

**Issue by buhman** [HalosGhost/pbpst#23]
Testcase:

```
$ ./src/pbpst -S
^C
$ ./src/pbpst -S
pbpst: Could not lock the database: File exists
pbpst: If no other instances of pbpst are running, you can delete /tmp/pbpst.lck
```
- [x] Remove errant/error-prone lockfile code
- [x] Handle signals to gracefully exit where possible

**Comment by HalosGhost** [comment]
Yep, we are aware of this issue. We're going to be completely redoing the locking setup. In fact, we're going to remove the global lockfile entirely, and infer locked status from the presence of a swap db after the db has been located. So, expect to see all this handling code changed.

**Comment by buhman** [comment]
I think you mean "bug" ;p

**Comment by HalosGhost** [comment]
We now handle `SIGINT` as gracefully as we can (I think). I would be willing to register other signals to use the same handler to fail out as gracefully as possible, but I'm not sure which other signals should be handled. Either way, the issue described in OP is taken care of.

via 97ea929
