### ISSUE TITLE
pbpst -Ss <url> throwing zsh: exit 23

### ISSUE THREAD

**Issue by halfwit** [HalosGhost/pbpst#28]
All attempts to shorten a URL fail
Using: Termite, zsh, pbpst-git-0.r145.7455180

No logging occurs with --verbose

**Comment by HalosGhost** [comment]
exit 23 is a libcurl error code that signals a write error. I am almost certain that this happens due to the write functions we added for the db tracking.

**Comment by HalosGhost** [comment]
via bcd8d67
