### ISSUE TITLE
Allow for specifying an extension for a file

### ISSUE THREAD

**Issue by HalosGhost** [HalosGhost/pbpst#29]
Some browsers (I'm looking at your Firefox) do not understand file MIMEtypes quite right, so image pastes will be served as if they are text in Firefox.

[Upstream is working on a possible fix](https://github.com/ptpb/pb/issues/128), but allowing users to specify an extension for us to return in the modified URL is a decent stop-gap anyway. Note that we will not be automatically detecting an extension to use; the user will need to specify one, or one will not be added.

Luckily, this is just adding an option (most likely `-e`) to `-S` and `-U` and modifying the callback to write it correctly.

**Comment by HalosGhost** [comment]
via a779c66

**Comment by buhman** [comment]
> [firefox does] not understand file MIMEtypes quite right

False. In fact it is not-firefox that is doing the wrong thing. pb told it `text/plain`, and firefox is obediently displaying `text/plain`. Any other behavior (chromium) is invalid--it doesn't matter if the body happens to be `image/png` or whatever.

**Comment by buhman** [comment]
> via a779c66

pb [already](https://github.com/ptpb/pb/commit/f92d6100c25308a6d4ae80abbbbdabaf1467689f) has that behavior server-side. meh.

**Comment by HalosGhost** [comment]
It does, I just added it locally. Has upstream corrected this issue to serve as not-`text/plain` yet?
