### ISSUE TITLE
Improve clarity on SIGINT

### ISSUE THREAD

**Issue by AladW** [HalosGhost/pbpst#35]
When pbpst recieves SIGINT, it doesn't remove the swap db. Currently pbpst only says this:

```
^Cpbpst: Received Interrupt
```

Perhaps we could expand on the message, so that "Could not create swap db" does not come unexpected.

**Comment by HalosGhost** [comment]
Is the error produced by fb7e505 clear enough to close?

**Comment by AladW** [comment]
Yep, thank you.
