### ISSUE TITLE
add terminal handler support

### ISSUE THREAD

**Issue by buhman** [HalosGhost/pbpst#40]
Rougly, you need to reimplement/combine [convert.rb](https://gist.github.com/sickill/504474702dd18c7dc0ec#file-convert-rb) and [terminal.c](https://github.com/asciinema/asciinema.org/blob/master/src/terminal.c) in pbpst.

Then a combined 'upload recording to pb' function would look something like:

``` bash
recpb() {
  asciinema rec /tmp/$$.json
  pbpst --convert /tmp/$$.json
}
```

I'm pretty sure the v1 json (asciinema output) contains things like recording duration information, whereas the player json (convert.rb/pbpst output) doesn't, so the other thing pbpst should do is emit that lost metadata in the query string: `https://ptpb.pw/t/<id>?d=<duration>`.

I believe in you.

**Comment by HalosGhost** [comment]
This will almost certainly not include `fork()`/`exec()` calls in `pbpst` itself; it will most likely just include an option under `-S` and `-U` similar to `-r` but for the terminal handler.

In the future however, we may allow some more integration using asciinema as an opt-dependency.

**Comment by HalosGhost** [comment]
via 55b3228
