### ISSUE TITLE
Unexpected error message without network access

### ISSUE THREAD

**Issue by AladW** [HalosGhost/pbpst#54]
Running `pbpst -S` obviously requires network access, but when there is none, there should be a clearer error message than: 

```
pbpst: wrong arguments at -1:-1
```

exit status: 1

**Comment by HalosGhost** [comment]
Interesting! Thanks for reporting!

**Comment by HalosGhost** [comment]
via fe44708

**Comment by AladW** [comment]
```
pbpst: Pasting failed: Couldn't resolve host name
```

Works for me, thanks :+1:
