### ISSUE TITLE
FILES section for pbpst(1)

### ISSUE THREAD

**Issue by AladW** [HalosGhost/pbpst#57]
From man-pages(7)

>  FILES   A list of the files the program or function uses, such as configuration files, startup files, and files the program directly  operates  on.
> Give  the  full pathname of these files, and use the installation process to modify the directory part to match user preferences.  For many programs, the default installation location is in /usr/local, so your base manual page should use /usr/local as the base.

This would include `$XDG_CONFIG_HOME/pbpst/db.json`, amongst others.

**Comment by HalosGhost** [comment]
Is 937afc8322dff51a274bc8c093b409e5cb4c6b6e an acceptable fix? What other files do you think should be included?

**Comment by AladW** [comment]
Looks good to me. How about also mentioning the `.swp` file (though the extension could also be mentioned in the `ERRORS` section) ?

**Comment by HalosGhost** [comment]
Oh, mentioning the swap file is a great idea. I will add that tonight.

**Comment by HalosGhost** [comment]
How about ab94e92b0bfb5de3022ef963a6610d618f546089?

**Comment by AladW** [comment]
Yep, this works, thanks.
