### ISSUE TITLE
Change progress flag to something that plays nice with all shells.

### ISSUE THREAD

**Issue by tmplt** [HalosGhost/pbpst#62]
Some shells, or at least zsh, uses the `#` character. This requires the flag to be quoted when using `pbpst`. I suggest this is changed to a `[a-zA-Z]` character.

I planned to suggest `-P` or `-T`, but both of those are in use already.

**Comment by HalosGhost** [comment]
`#` is used mostly because `curl` uses it. However, I use zsh and do not find myself having to quote `-#`. Under what circumstances do you find yourself needing to quote it?

Also note that because `--progress` is valid, if that were ever a concern, you can fall back to it.

**Comment by tmplt** [comment]
I tried using `-#` in `zsh -f` and it appears that my zsh framework ([zim](https://github.com/Eriner/zim)) makes use of `#`. I was unaware of that.

**Comment by HalosGhost** [comment]
Ahh, I see. I am afraid I am not terribly moved to change this since it is cosmetic for most, and, again, is the flag chosen by the utility of our parent library. If you cannot make zim behave more normally, then I'd recommend using `--progress`.

**Comment by tmplt** [comment]
> is the flag chosen by the utility of our parent library.

Understandable. I wouldn't change it either, especially as this issue isn't actually `pbpst`-based. This issue is closed for my part.
