### ISSUE TITLE
Pbpst doesn't like http to https redirects

### ISSUE THREAD

**Issue by ghost** [HalosGhost/pbpst#64]
pbpst gives errors when a paste is attempted that gets redirected. 

Please see asciinema w/ description of issue...
https://asciinema.org/a/9gqk7gtvstgu4oksoxp58y4xu

**Comment by HalosGhost** [comment]
For now, I am just going to detect if the provider is `http` and not `https` and throw an error.

In the future, I may allow for `http`-based providers, but since `pb` defaults to `https`-only and I would rather enforce security than enable insecurity.

**Comment by HalosGhost** [comment]
via 4c4990e29e9c47d4e9ea51a8f0c68d5ec19f9d9a
