### ISSUE TITLE
doc/pbpst.rst line 220+225 indentation errors?

### ISSUE THREAD

**Issue by ghost** [HalosGhost/pbpst#69]
Section of my build which gives non-fatal errors:

Running Sphinx v1.2.3
building [man]: 2 source files given on command line
updating environment: 2 added, 0 changed, 0 removed
reading sources... [ 50%] pbpst
reading sources... [100%] pbpst_db

/tmp/guix-build-pbpst-1.2.0-1.4aeb782.drv-0/source/doc/pbpst.rst:220: ERROR: Unexpected indentation.
/tmp/guix-build-pbpst-1.2.0-1.4aeb782.drv-0/source/doc/pbpst.rst:225: ERROR: Unexpected indentation.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... pbpst.1 { } pbpst_db.5 { } 
build succeeded, 2 warnings.

**Comment by HalosGhost** [comment]
via a26cbcef67cf3ea3a9734b1f31e1256215b117d2
