### ISSUE TITLE
Errors on use of stderr

### ISSUE THREAD

**Issue by HalosGhost** [HalosGhost/pbpst#79]
https://ptpb.pw/hVCd.png

**Comment by tmplt** [comment]
In case it helps, latest HEAD builds without issue on my system with clang 3.9.1.

**Comment by HalosGhost** [comment]
Interesting. I will look into this more and see what I can see.

**Comment by HalosGhost** [comment]
@oatberry, can you add some more information here?

**Comment by HalosGhost** [comment]
Okay, I believe I have this figured out. C89 and C99 specify that ``stdout``, ``stdin`` and ``stderr`` are macros. But, because of how these macros are defined in musl libc, the compiler detects a recursive macro expansion.

I think it is safe to say that these issues are common enough and uninteresting enough that we should probably whole-sale disable this warning.

**Comment by HalosGhost** [comment]
via 657cde14ae4e18df8c90f72b2cba04ecad326154
