### ISSUE TITLE
Does it support authentication

### ISSUE THREAD

**Issue by amosbird** [HalosGhost/pbpst#81]
I just set up a private pb and I don't want others to post content to it. Can I achieve this by pbpst?

**Comment by amosbird** [comment]
Ok, I just hard coded one :smiley:

**Comment by tmplt** [comment]
I wasn't aware pb authentication was possible. Could you share your changes? I'm sure it would make a good addition.

**Comment by HalosGhost** [comment]
pb does not natively support any authentication method. I would be interested in seeing the changes as well.

**Comment by amosbird** [comment]
well, i just use nginx to do the proxy and authentication, and add `curl_easy_setopt(handle, CURLOPT_USERPWD, userpwd);` to pbpst :smiley:

**Comment by HalosGhost** [comment]
Ahh, I see. Fair enough. Be careful to not accidentally use a different provider since you will send your user password to the other provider as well (which will—at best—leak the password to the other provider, and—at worst—cause pbpst to crash horribly somehow).
